DROP TABLE IF EXISTS PEPPOL_DOCUMENT;

CREATE TABLE PEPPOL_DOCUMENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  status VARCHAR(250) NOT NULL
);

INSERT INTO PEPPOL_DOCUMENT (status) VALUES
  ('FAILED'),
  ('BLOCKED'),
  ('FAILED')